version: 0.0
os: linux
files:
  - source: /
    destination: /home/bitnami/express-app
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: bitnami
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: bitnami
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: bitnami