GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA4YzEyMmYyNmMzOGJhMzU2ZWMxZTMiLCJsaXN0aW5nX2lkIjoiMSIsImxhc3RfbW9kaWZpZWQiOiIyMDIyLTAyLTEzVDA4OjI4OjE4LjgyN1oiLCJ1c2VybmFtZSI6Im90c29qbSIsImZpcnN0X25hbWUiOiJPdHNvIiwibGFzdF9uYW1lIjoiSk0iLCJlbWFpbCI6Im90c29qbUBsb2NhbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQwYXVVTnFHYmM1Tk05OXg1TmE5MDNlM0ZBMHpMSk1IT1BjMWZ6YWpQdmQ2RldyZE5Ld0tlZSIsImlhdCI6MTY0NDc0NTI4Mn0.ONpp__XJCmd-PPnVw-nc-ANbfFG1ifIZNYpIP5bvTHc

###

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA4Y2I1NDg5ZDVkMTVlZWY4ZGVlMzQiLCJsaXN0aW5nX2lkIjoiMiIsImxhc3RfbW9kaWZpZWQiOiIyMDIyLTAyLTEzVDA5OjExOjQ4LjM3OVoiLCJ1c2VybmFtZSI6Im90c29qbTIiLCJmaXJzdF9uYW1lIjoiT3RzbyIsImxhc3RfbmFtZSI6IkpNIiwiZW1haWwiOiJvdHNvam1AbG9jYWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkN1FqTzROaUFYUzFTNGFsU0FNL2FCZXpOSi41Sm0wdElRQUZFbUVxRjJjTzB0bFoweDlMSFMiLCJpYXQiOjE2NDQ3NDU0Nzh9.BJ7qnx8j0t4NxRX1JKKkzHciTJoYyHtpLVkjqhJKE7U

